### ISSUE TITLE
[Request]: Make xkbcommon optional

### ISSUE THREAD

**Issue by Quackdoc** [pop-os/libcosmic#782]
When cross compiling cosmic applications it can be very useful to be able to disable dependencies that require native libraries. In the case of libcosmic, the only offender here is xkbcommon. 

As a proof of concept I patched various deps to disable xkbcommon crate, cross compiled to gnu arm `cargo build --release --target aarch64-unknown-linux-gnu`, loaded it on my phone and ran it. The application in question that I used was cosmic-edit, the patches below, wayland worked fine, x11 has broken keyboard input (though this is possibly a winit related issue as some other other winit applications share similar issues, for context prior discussion is here https://github.com/YaLTeR/niri/issues/713)

(note I had to patch [dev-dependnecies] too for these which is why they are here)
```toml
[patch.'https://github.com/Smithay/smithay-clipboard']
smithay-clipboard = { path = "./smithay-clipboard" }

[patch.'https://github.com/pop-os/smithay-clipboard']
smithay-clipboard = { path = "./pop-clipboard" }

[patch.'https://github.com/pop-os/cosmic-protocols']
cosmic-client-toolkit = { path = "./cosmic-protocols/client-toolkit" }
```

It would be nice to be able to conveniently cross compile libcosmic applications.
